{{- if .Values.sentry.token.create }}
{{- if not .Values.sentry.token.value }}
{{- fail "sentry.token.create is true but sentry.token.value is empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debugsymd.fullname" . }}-sentry
  labels:
    {{- include "debugsymd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sentry.token.key }}: {{ .Values.sentry.token.value | quote }}
{{- end }}
